### ISSUE TITLE
Story 9: Viewing past orders

### ISSUE THREAD

**Issue by tmikeschu** [akintner/scoopful#75]
Background: An existing user that has multiple orders
As an Authenticated User
When I visit "/orders"
Then I should see all orders belonging to me and no other orders

**Comment by tmikeschu** [comment]
@kheppenstall is getting started on users, but I think a lot of this can be built out by stubbing a user or by making orders without users, and we will bring in user later on.

**Comment by tmikeschu** [comment]
@akintner : #76 builds on this, so keep us posted on your progress.

**Comment by akintner** [comment]
Ok, sounds good. I'm just starting now.
