### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by case-eee** [akintner/scoopful#84]
1. love all the commits. y'all rock 🎉 

2. good use of `to_param`

3. great use of partials 👍 

@kheppenstall @wlffann @tmikeschu @akintner i don't have much critical feedback for ya! woooooo using haml. keep up the great work 🎉

**Comment by tmikeschu** [comment]
Thanks for taking a look, @case-eee !

**Comment by case-eee** [comment]
of course!
